export const users = [
    { username: 'admin', password: 'admin@123', userType: 1, firstName: 'Sam', lastName: 'Karen', mobileNumber: '9876543210' },
    { username: 'balaji', password: 'balaji@123', userType: 2, firstName: 'Balaji', lastName: 'KT', mobileNumber: '9988776655' },
    { username: 'paul', password: 'paul@123', userType: 2, firstName: 'Paul', lastName: 'Mark', mobileNumber: '9876598765' },
    { username: 'ganesh', password: 'ganesh@123', userType: 2, firstName: 'Ganesh', lastName: 'Arumugam', mobileNumber: '8787656543' },
];

export const transactions:any[] = [
    {
        id: 1,
        customerName: 'John Doe',
        customerType: 'New',
        customerNumber: '1234567890',
        customerAddress: '123 Main St',
        customerPhone: '555-1234',
        transferAmount: 1000,
        transferCurrency: 'USD',
        beneficiaryBank: 'Some Bank',
        beneficiaryAccountNumber: '0987654321',
        paymentDetails: 'Payment for Services',
        cardDetails: '1234 ** ** 5678',
        region: 'North America',
    },
    {
        id: 2,
        customerName: 'Paul',
        customerType: 'New',
        customerNumber: '1234567890',
        customerAddress: '123 Main St',
        customerPhone: '555-1234',
        transferAmount: 1000,
        transferCurrency: 'USD',
        beneficiaryBank: 'Some Bank',
        beneficiaryAccountNumber: '0987654321',
        paymentDetails: 'Payment for Services',
        cardDetails: '1234 ** ** 5678',
        region: 'North America',
    },
    {
        id: 3,
        customerName: 'Balaji',
        customerType: 'New',
        customerNumber: '1234567890',
        customerAddress: '123 Main St',
        customerPhone: '555-1234',
        transferAmount: 1000,
        transferCurrency: 'USD',
        beneficiaryBank: 'Some Bank',
        beneficiaryAccountNumber: '0987654321',
        paymentDetails: 'Payment for Services',
        cardDetails: '1234 ** ** 5678',
        region: 'North America',
    },
    {
        id: 4,
        customerName: 'saravanan',
        customerType: 'New',
        customerNumber: '1234567890',
        customerAddress: '123 Main St',
        customerPhone: '555-1234',
        transferAmount: 1000,
        transferCurrency: 'USD',
        beneficiaryBank: 'Some Bank',
        beneficiaryAccountNumber: '0987654321',
        paymentDetails: 'Payment for Services',
        cardDetails: '1234 ** ** 5678',
        region: 'North America',
    },
];